{
    "name": "thyme-to-grow",
    "env": {
        "NODE_VERSION": "18.x"
    },
    "build": {
        "env": {
            "NODE_ENV": "production"
        }
    },
    "startCommand": "node server.js",
    "healthCheckPath": "/",
    "envVarGroups": [
        {
            "name": "production",
            "envVars": [
                {
                    "key": "NODE_ENV",
                    "value": "production"
                },
                {
                    "key": "MONGO_URI",
                    "sync": false
                },
                {
                    "key": "JWT_SECRET",
                    "sync": false
                }
            ]
        }
    ]
}
