services:
  - type: web
    name: thyme-to-grow
    env: node
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
    ports:
      - port: 10000
